name: Fuzz wordipelago APWorld
on:
  push:
    branches: '*wordipelago*'
  pull_request:
    branches: '*wordipelago*'


jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: Eijebong/ap-actions/fuzz@main
        with:
          apworld-path: worlds/wordipelago
          ap-version: '0.6.6'
          python-version: '3.12'
          yamls-per-run: 3
