name: Release wordipelago APWorld
on:
  push:
    tags:
      - '*wordipelago*'
jobs:
  release:
    uses: Eijebong/ap-actions/.github/workflows/release-apworld.yml@main
    with:
      apworld-path: worlds/wordipelago
      ap-version: '0.6.6'
      python-version: '3.12'